MODEL:
  BACKBONE: VGG16_13_Stage
  INIT: (0.9, 0.1)
  NET1_CLASSES: 25
  NET2_CLASSES: 4
TRAIN:
  EVAL_CKPT: True
  LOG_INTERVAL: 1
  LR: 0.0001
  SAVE_INTERVAL: 5
  WEIGHT_1: Seg
  WEIGHT_2: Normal