MODEL:
  BACKBONE: VGG16_13_Stage
  INIT: (0.9, 0.1)
  NET1_CLASSES: 25
  NET2_CLASSES: 4
TRAIN:
  EVAL_CKPT: False
  LOG_INTERVAL: 5
  LR: 0.00001
  SAVE_INTERVAL: 100
  WEIGHT_1: Seg
  WEIGHT_2: Normal
