MODEL:
  BACKBONE: VGG16_13_Stage
  INIT: (0.9, 0.1)
  NET1_CLASSES: 25
  NET2_CLASSES: 4
TRAIN:
  EVAL_CKPT: True
  LOG_INTERVAL: 20
  LR: 0.0001
  SAVE_INTERVAL: 5000
  WEIGHT_1: Seg
  WEIGHT_2: Normal
